name: Record Stream

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: 'Target Room Web URL'
        required: true
        default: ''

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yt-dlp & FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Download Stream
        run: |
          yt-dlp "${{ github.event.inputs.stream_url }}" -o "output.mp4" --concurrent-fragments 5

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: recorded-stream
          path: output.mp4
          retention-days: 1
